In [1]:
from multiprocessing import Process , Queue , Manager
from threading import Thread
import numpy as np
import cv2
import Source as S

In [2]:
manager= Manager()
OnlineQ = manager.Queue()
FrameQ = manager.Queue()
Q=manager.Queue()

In [3]:
S.Create(8080)
client = S.Accept()

In [4]:
R_Thread = Thread(target=S.R_Thread, args=(client,FrameQ,OnlineQ))
R_Thread.start()  # Reciv Thread Start

#T_Thread = Process(target=S.T_Thread, args=(client,Q,OnlineQ))
#T_Thread.start()


Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\subeen/.cache\torch\hub\master.zip
YOLOv5  2022-6-8 Python-3.9.12 torch-1.11.0+cpu CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7018216 parameters, 0 gradients
Adding AutoShape... 


[     80.921      69.867      139.95      204.79     0.85508           0]
[     81.573      72.805      138.26      205.03     0.85025           0]
[     80.738      70.373      139.27      205.34     0.83152           0]
[     81.579      69.023      141.44      200.43     0.86258           0]
[     83.593      64.702      142.12      197.65     0.89061           0]
[     79.693      62.884      141.84      199.13     0.89626           0]
[     78.831      62.372      140.92      199.25     0.88587           0]
[     80.017      64.378      140.63      200.47     0.87149           0]
[     82.326      62.349      142.76      198.83     0.87679           0]
[     84.591      60.284      144.56      196.19     0.90765           0]
[     86.348       59.59      147.06      195.85     0.90327           0]
[     87.572      56.305      147.87       194.9     0.90483           0]
[     87.883      54.453      149.38      192.47     0.90789           0]
[     70.691      30.727      142.45  

유리가 아님
[     204.63      49.321       274.1      218.29     0.79024           0]
유리가 아님
[     204.06        48.5      274.36      218.38     0.79174           0]
유리가 아님
[     203.41      47.856      273.93       217.8     0.80428           0]
유리가 아님
[     205.56      46.405      274.52      217.39     0.74679           0]
유리가 아님
[     204.75      45.917      274.37      216.93     0.74371           0]
유리가 아님
[     201.94      48.598      272.29      218.37      0.8046           0]
유리가 아님
[     201.34      48.753       271.6      218.36     0.79588           0]
유리가 아님
[     202.89      48.495      272.64      217.71     0.80679           0]
유리가 아님
[     201.71      48.445       271.7      218.32     0.80062           0]
유리가 아님
[     201.42      49.599      271.73      218.42     0.80261           0]
유리가 아님
[     201.83       50.43      272.04      218.17     0.80222           0]
유리가 아님
[     202.87       50.18      272.49      217.95      0.7929           0]
유리가 아님
[     203.13      50.

[     134.75           0      230.78      120.74     0.79535           0]
[     106.83     0.51747      233.37      107.26     0.78187           0]
[          0      47.141      110.36      185.01     0.91887           0]
[          0      44.671      108.49       188.8     0.92129           0]
[          0      45.361      109.52      188.39     0.91888           0]
[          0      50.592      113.59      186.67     0.91936           0]
[          0      48.309      112.89       191.4     0.91161           0]
[          0      47.009      113.94      193.01     0.91962           0]
[    0.48426      47.137      113.76      201.85     0.91093           0]
[    0.95743      47.385      113.18      203.82     0.91025           0]
[          0      51.543      118.05      190.25     0.90747           0]
[          0      51.845      117.13      190.44      0.9102           0]
[          0      50.364      118.44      191.54     0.91271           0]
[          0      49.193      119.03  

[     168.74      150.22      214.08      208.15     0.67498           1]
[     173.63      131.99      216.05      205.05     0.79765           1]
[     176.46      111.61      222.99      200.82     0.85991           1]
[     179.28      91.452      227.45         207     0.88184           1]
[     180.63      80.632      227.39      201.28     0.90672           1]
[     180.69      65.965      226.32      196.46     0.88157           1]
[     179.44      50.213      228.51       174.4     0.89171           1]
[     179.28      40.155      227.65      164.84     0.89086           1]
[     176.86      28.437      228.77      160.28     0.91946           1]
[     176.38      23.647      227.64      156.86     0.91186           1]
[     170.02      22.627      228.08      171.32      0.9073           1]
[     170.55      18.415      229.17      169.66     0.94162           1]
[     170.56       15.33      229.35      168.68     0.94817           1]
[     170.58      15.254       230.3  

[      190.3      53.871      254.57      213.09     0.92854           1]
[     199.95      53.803      263.49      218.38     0.95258           1]
[     200.06      55.709      263.02       220.5     0.95624           1]
[     200.55      56.322      262.66      221.28     0.94621           1]
[     200.64      59.396      262.35      222.81     0.94082           1]
[     201.93      62.566      263.14      223.58     0.92325           1]
[     203.98      62.199      264.94      226.54     0.91257           1]
[     203.89      62.366      265.62      226.01     0.90671           1]
[     202.36      63.409      265.48      223.87     0.91101           1]
[     201.79      61.187      265.39      221.04     0.92976           1]
[     202.03      60.753      265.69      220.15      0.9334           1]
[     202.81      60.872      265.86      219.81     0.93384           1]
[     202.57      58.585      265.57      219.33     0.93929           1]
[     201.54      56.482      265.46  

캔이 아님
[   0.051241      87.877      135.18      227.06      0.7155           1]
캔이 아님
[     2.4358      87.183      135.44      215.56     0.77156           1]
캔이 아님
[     1.7885      87.369      135.13      217.34     0.72572           1]
캔이 아님
[     1.9759      87.535      134.47      214.17     0.70367           1]
캔이 아님
[     2.4247       85.78      133.96      210.71     0.67554           1]
캔이 아님
[     3.7814       86.41      132.66      213.11     0.75001           1]
캔이 아님
[     6.1117       84.92      130.76      209.54     0.82588           1]
캔이 아님
[     6.0044      83.748      128.63      219.23     0.81757           1]
캔이 아님
[     4.6239      86.959      130.33      218.47     0.80044           1]
캔이 아님
[      5.013      86.757      130.49      216.74     0.80624           1]
캔이 아님
[      3.769      56.965      111.77      200.04     0.87714           1]
캔이 아님
[     2.7232      54.856      110.18      197.32     0.87666           1]
캔이 아님
[      1.848      55.538      109.

[     133.01      79.915      252.61      184.93     0.60631           1]
[     340.03           0      410.55      149.76     0.89226           1]
[     339.51           0      411.55      158.21     0.87479           1]
플라스틱이 아님
[     345.55           0      411.67       161.6     0.89413           1]
플라스틱이 아님
[     347.16     0.57621      412.97      163.35     0.89976           1]
플라스틱이 아님
[     348.78      4.6635      412.81      168.05     0.89709           1]
플라스틱이 아님
[     348.67      1.5055      413.84      172.64       0.925           1]
플라스틱이 아님
[     349.67      4.8642      414.29      174.12     0.93947           1]
플라스틱이 아님
[     349.55      7.0133         415      176.16     0.94643           1]
플라스틱이 아님
[     350.38      8.9513      415.07      175.39     0.94069           1]
플라스틱이 아님
[     349.69      8.4988      415.19      175.43     0.94258           1]
플라스틱이 아님
[     353.49      7.7809      414.84      175.55     0.93522           1]
플라스틱이 아님
[     347.71       4.6

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\subeen\anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\subeen\anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\subeen\Desktop\doge\server\Source.py", line 44, in R_Thread
    stringData = recvall(client, int(length))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


In [5]:
OnlineQ.put(0)

Server_R_Thread_OFF


In [6]:
Q.put(1)

In [19]:
Q.qsize()

0

In [16]:
FrameQ.qsize()

153